### ISSUE TITLE
ProcessorSetup class

### ISSUE THREAD

**Issue by mabar** [orisai/object-mapper#8]
For apps without DIC and simpler tests setup

```
$setup = new ProcessorSetup();
$setup->withRuleManager(...)
	->withObjectCreator(...);
$processor = $setup->build();
```

**Comment by mrceperka** [comment]
Looks like a builder to me :D

**Comment by mabar** [comment]
> Looks like a builder to me :D

I guess~

**Comment by mabar** [comment]
Closed by https://github.com/orisai/object-mapper/commit/f3cca251c67f8a9af8dcf7b84f07073c467d13be
